
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\jhasa\OneDrive\Desktop\GameVerse\GameVerse\assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("887x519")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 519,
    width = 887,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    420.0,
    0.0,
    887.0,
    519.0,
    fill="#AC10BD",
    outline="")

canvas.create_text(
    50.0,
    66.0,
    anchor="nw",
    text="Login",
    fill="#342E2E",
    font=("IstokWeb Bold", 30 * -1)
)

canvas.create_rectangle(
    47.0,
    106.0,
    80.0,
    109.0,
    fill="#6800BE",
    outline="")

entry_image_1 = PhotoImage(
    file=relative_to_assets("Login_entry_1.png"))
entry_bg_1 = canvas.create_image(
    182.5,
    215.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0,
    font=("IstokWeb",12)
)
entry_1.place(
    x=60.0,
    y=192.0,
    width=245.0,
    height=49.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("Login_entry_2.png"))
entry_bg_2 = canvas.create_image(
    182.5,
    330.5,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0,
    font=("IstokWeb",12)
)
entry_2.place(
    x=60.0,
    y=307.0,
    width=245.0,
    height=49.0
)

canvas.create_text(
    54.0,
    160.0,
    anchor="nw",
    text="Username",
    fill="#000000",
    font=("IstokWeb Bold", 18 * -1)
)

canvas.create_text(
    54.0,
    274.0,
    anchor="nw",
    text="Password",
    fill="#000000",
    font=("IstokWeb Bold", 18 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("Login_button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=54.0,
    y=360.0,
    width=117.0,
    height=21.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("Login_button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=111.0,
    y=414.0,
    width=121.0,
    height=42.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("Login_button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=13.0,
    y=489.0,
    width=233.0,
    height=25.0
)
window.resizable(False, False)
window.mainloop()
